### PR TITLE
first stab with Plotly and Calc Assignment

### PR DESCRIPTION
**Pull request by mjsteele2099**
I made a folder for some Plotly work. I am learning about the functionality and planning to make some cool graphs with MPGs and other automotive stuff. 

From there I can plot some other stuff for our project.

Nothing cool here asI need to do a little more learning.

### CODE REVIEW

**Comment by davek612** [comment]
Impressive!

**Review by davek612 — DISMISSED** [review]
Impressive!

**Review by kaanvat — APPROVED** [review]
Looks good to me :)

**Review by Rainman21 — APPROVED** [review]
Looks good

**Pull request merged**
